name: LaTeX to PDF

on:
  push:
    branches:
      - master
      - translation/en
    tags:
       - '*'
  pull_request:
    branches:
      - master
      - translation/en

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Guix cache"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/guix"
          # Guix cashed once a day; the first build will be slow but the
          # subsequent builds on the current day will be faster.
          key: "guix-cache-x86-${{ steps.date.outputs.date }}"
          restore-keys: |
            guix-cache-x86-
      - name: "Install Guix"
        uses: "PromyLOPh/guix-install-action@v1"
      - name: "Ensure no locale warning"
        run: |
          test -z "$(guix --version 2>&1 >/dev/null)"
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: Build the book
        run: |
          guix build --file=guix.scm
      - name: Install the book
        run: |
          guix package --install-from-file=guix.scm
      - name: Upload the Russian version of the book as PDF
        id: upload-workflow-tab
        uses: actions/upload-artifact@v4
        with:
          name: avp-sparc-book-ru-pdf
          path: "~/.guix-profile/share/doc/sparc/sparc.ru.pdf"
      - name: Upload the English version of the book as PDF
        id: upload-workflow-tab
        uses: actions/upload-artifact@v4
        with:
          name: avp-sparc-book-en-pdf
          path: "~/.guix-profile/share/doc/sparc/sparc.en.pdf"
